#!/bin/bash

usage() {
	bin=$(basename $0)
	echo >&2 "Usage: $bin"
	exit ${1:-0}
}
[[ "$1" = -h || "$1" = --help || $# -ne 0 ]] && usage

set -e -o pipefail
export LC_ALL=C

[[ -e /etc/apk/world ]] || { echo >&2 "apk-world file is missing"; exit 1; }

apk list -I | awk '{print $1, $3}' | sort -u >/etc/apk/world.all
apk list -O | awk '{print $1, $3}' | sort -u >/etc/apk/world.extras
awk '/></ {split($0,a,">"); print a[1]}' /etc/apk/world | sort -u >/etc/apk/world.custom

rc-update show -v | awk '{print ($3 ? $3 : "~") "." $1}' | sort -u >/etc/apk/site.rc

updatedb
locate -e --regex '\.apk-new$' >/etc/apk/site.conf-diffs ||:
find /usr/local -xdev -mindepth 1 | sort >/etc/apk/site.local
