#!/usr/bin/env python

import os, sys, re, time, logging, enum, threading, queue
import json, signal, atexit, base64, unicodedata as ud, hashlib as hl
import subprocess as sp, functools as ft, textwrap as tw

import auparse # https://github.com/linux-audit/audit-userspace/


class adict(dict):
	def __init__(self, *args, **kws):
		super().__init__(*args, **kws)
		self.__dict__ = self

def no_exc(func, *args, exc=ValueError, **kws):
	try: return func(*args, **kws)
	except exc: pass

def str_hash(s, c=None, key=b'auid-tag', strip=''):
	s_raw, s = s, base64.urlsafe_b64encode(
		hl.blake2s(str(s).encode(), key=key).digest() ).decode()
	if not isinstance(strip, dict): strip = dict.fromkeys(map(ord, strip + '-_='))
	s = s.translate(strip)
	if c is None: return s
	for n in range(30): # limit is to avoid unlikely a -> ... -> a loops
		if len(s) < c: s = str_hash(s, c, key, strip)
		if len(s) >= c: break
	else: raise RuntimeError(f'str_hash() failed on: {s_raw!r} {[c, key, strip]}')
	return s[:c]


class au_str(str): __slots__ = 't', # .t stores unrepresentable key/type str
input_fmt = enum.Enum('InputFormat', 'journal auditd syslog')
input_apt = enum.IntEnum('InputAuditTypes', dict(
	(k[13:].lower(), getattr(auparse, k))
	for k in dir(auparse) if k.startswith('AUPARSE_TYPE_') ))

def input_parse(stream, fmt=None, noise_filter=None, flush_timeout=0.1):
	def _line_q():
		for line in stream: q.put(line)
		q.put(None)
	q, proc = queue.Queue(3), adict(
		fmt=fmt, init=False, wait=False, log=logging.getLogger('parse') )
	threading.Thread(target=_line_q, name='lineq', daemon=True).start()
	while q:
		try:
			if (line := q.get(timeout=flush_timeout)) is None: q = None
			yield from input_parse_line(proc, line, noise_filter)
		except queue.Empty: yield from input_parse_line(proc)

def input_parse_line(proc, line=None, noise_filter=None):
	if not line:
		if proc.init:
			proc.ap.flush_feed()
			if evs := proc.evs.copy(): proc.evs.clear(); yield from evs
		return

	st = adict(auid=None, dec=False)
	if isinstance(line, bytes): st.dec, line = True, line.decode(errors='replace')
	if not line.strip(): return

	if not proc.fmt:
		import datetime as dt
		if line[0] == '{': proc.fmt = input_fmt.journal
		elif line.startswith('type='): proc.fmt = input_fmt.auditd
		elif line[0].isdigit() and no_exc( # some time-prefixed syslog format
			dt.datetime.fromisoformat, line.split(None, 1)[0] ): proc.fmt = input_fmt.syslog
		else: raise ValueError( 'Failed to recognize'
			' input stream format from first line:\n  {line!r}' )
	if not proc.init:
		proc.update( init=True, j=False, fix_qs=False, evs=list(),
			ap=auparse.AuParser(auparse.AUSOURCE_FEED), ap_cb=( lambda ap, cbt, evs:
				cbt == auparse.AUPARSE_CB_EVENT_READY and evs.extend(input_parse_ev_list(ap)) ) )
		proc.ap.add_callback(proc.ap_cb, proc.evs)
		if proc.fmt is proc.fmt.journal: proc.update( j=True,
			id_fields=lambda o,_ks=( '__monotonic_timestamp syslog_facility'
				' syslog_identifier message'.upper().split() ): tuple(o.get(k) for k in _ks) )
		elif proc.fmt is proc.fmt.auditd: pass
		elif proc.fmt is proc.fmt.syslog: proc.fix_qs = True
		else: raise ValueError(f'Unrecognized format: {fmt}')

	if proc.j:
		ts, log_fac, log_id, line = proc.id_fields(data := json.loads(line))
		if (log_fac, log_id) == ('0', 'kernel') and line.startswith('audit: type='): st.auid = True
		elif (log_fac, log_id) == ('4', 'audit'): st.auid = data.get('_AUDIT_ID')
		else: st.auid = False # skip non-audit line
	else: line = line.strip()

	if st.auid is False or not (m := re.fullmatch(
			r'((.*? )?audit: )?(?P<rec>type=\S+'
			r' (msg=)?audit\((?P<auid>(?P<ts>[\d.]+)(:\d+)?)\):\s+.*)', line )):
		if st.auid: proc.log.warning(
			'Unsupported audit line format%s: %r', st.dec and ' (decoded)' or '', line )
		elif noise_filter and noise_filter(line): yield line
		else: proc.log.debug('Skipping line: %r', line)
		return
	line = m['rec'] or line

	if proc.fix_qs: # encode field="stuff with spaces" from syslog for auparse
		parts = list()
		while True:
			line = ls[1] if len(ls := line.split(' ', 1)) > 1 else ''
			if '="' in ls[0] and ls[0][-1] != '"':
				k, v = ls[0].split('"', 1)
				while True:
					line = vs[1] if len(vs := line.split(' ', 1)) > 1 else ''
					vs = vs[0]; v += f' {vs}'
					if v.endswith('"'): break
					elif not line: v += '"'; break
				ls[0] = k + v[:-1].encode().hex()
			if '=' in ls[0] and any(c < 0x21 or c > 0x7e for c in ls[0].encode()):
				k, v = ls[0].split('=', 1)
				if v and v[0] == v[-1] == '"': v = v[1:-1]
				ls[0] = f'{k}={v.encode().hex()}'
			parts.append(ls[0])
			if not line: break
		line = ' '.join(parts)

	proc.ap.feed(f'{line}\n')
	if evs := proc.evs.copy(): proc.evs.clear(); yield from evs

def input_parse_ev_list(ap):
	evs = list()
	while True:
		evs.append(input_parse_ev(ap))
		if not ap.parse_next_event(): break
	return evs

def input_parse_ev(ap):
	auev = ap.get_timestamp(); ev = adict( rs=list(),
		auid=f'{auev.sec}.{auev.milli}:{auev.serial}',
		ts=auev.sec + auev.milli / 1000, ts_n=auev.serial )
	ap.first_record()
	while True:
		ev.rs.append(rec := adict())
		while True:
			k, t = ap.get_field_name(), no_exc(input_apt, ap.get_field_type())
			if not k or k[0] == '_' or callable(getattr(rec, k, None)):
				au_k = k[1:] if k.startswith('_') else k
				au_k = au_str(f'au_{au_k}'); k, au_k.t = au_k, k # original key in .t
			if t is input_apt.escaped_file: v = ap.interpret_realpath()
			elif t and t in (t.proctitle, t.escaped, t.escaped_key, t.success):
				v = ap.interpret_field()
				if v == '(null)' or v == '(none)': v = None
			else:
				try: v = ap.interpret_field()
				except ValueError: v = ap.get_field_str()
				if v == '(null)' or v == '(none)': v = None
				else: (v := au_str(v)).t = t and t.name or None
			if k == 'key' and v: ev.key = v
			rec[k] = v
			if not ap.next_field(): break
		if not ap.next_record(): break
	return ev

def format_record_line(evr, val_esc=''):
	'Adds evr._line from all record keys except "type" and internal underscored ones'
	line = ''
	for k, v in evr.items():
		if ( k[0] == '_' or v is None or
			(k == 'seresult' and re.fullmatch(r'audit\(\S+\):', v)) ): continue
		if re.search(r'[\x00-\x20\x7f]', str(v)) or any(
			ord(c) > 127 and ud.category(c)[0] in 'CZ' for c in str(v) ): v = json.dumps(v)
		line += ' ' + (f'{k}={v}'.replace(' ', val_esc) if val_esc else f'{k}={v}')
	if (line := line.lstrip()) == evr.get('_line_esc'): return # to keep any evr._line tweaks
	line = evr._line = evr._line_esc = line
	if val_esc: evr._line = line.replace(val_esc, ' ')

def format_event(evrs, twx=None, val_esc='', prefix=False):
	fmt = ( (lambda evr: (evr._prefix if prefix else '') + evr._line) if not (twx and val_esc)
		else lambda evr: (evr._prefix if prefix else '') + evr._line_esc.replace(val_esc, ' ') )
	return '\n'.join(fmt(evr) for evr in evrs if evr._line)


filter_file_info = r'''
Information on format for audit-follow script's -f/--filter-file option.

File is a list of filtering rules, which match against either
 possibly-multiline auditing event or one of its "audit record" lines,
 prefixed by either hyphen+space ("- <rule>") to remove event/record, or "+" to keep it.
All rules are evaluated in the same order as written against audit events,
 stopping on first record/event match, printing/keeping anything that falls through otherwise.
All non-audit-related lines are dropped by default, but can be
 passed through if they match any special "++" rules, that only apply to those.
It's the same idea with list of allow/drop rules as in firewall or rsync filters.

#-comments are ignored, where # must either start the line, or space-separated if inline.
Lines starting with space will continue previous line, with single-space prefix stripped.
Format for all regexps is PCRE-like, as implemented in python "re" module - see docs for it.
Trailing spaces on lines are always ignored, if any.

Non-comment/empty lines are in the form of either "- <rule>", "+ <rule>" or "++ <rule>".
"++" rules for non-audit lines don't have any "fields" or "event" concept, only match regexps.
<rule> is read as regexp to filter audit records by default, but also support special formats:
/<regexp>/ -- wrapped regular expression, with more clear start/end boundaries.
/<rx1>/ && /<rx2>/ -- combining multiple wrapped regexps using AND logic.
<flags>/<regexp>/ -- adding single-character flags for wrapped regexps, which can be:
  Flag: ! - negate regexp match, i.e. only apply replacement(s) or filtering if it doesn't match.
   Should only be useful for filtering (omitted/empty replacement), or in combination, e.g.:
   !/ apparmor=ALLOWED / && /.* apparmor=.* class=file.* name="(.*?)" .*/ => aa-file-issue: \1
  Flag: E - apply regexp over combined records of audit event (can be multiple lines),
   instead of individual records, with events formatted as they're printed with --raw option.
   IMPORTANT: if regexp with E flag is only/last in rule, whole event is printed/dropped.
  Flag: I - for a case-sensitive lookup, e.g. "I/SAN/", instead of default case-insensitive "i".
  Flag: M - full-match from beginning to end, as opposed to default "m" search.
  Python "re" module supports more regexp modifiers, e.g. "(?.)" for multiline matches.
<field>~<regexp> -- regexp-match for specific record/event field (or empty string if missing).
  "E" flag for wrapped regexp will match events, i.e. "match field in any record within event".
<field>==<value> -- match exact value of a field, instead of regexp-matches.
  If <value> starts with a double-quote, it'll be read as json string
   until next (closing) double-quote (escape any " in-between as "" or \u0022).
<field>=<flags>=<value> -- same flags as for regexps above, but applied for exact-string match.
  "m" flag can be used to search for substring, instead of default "M" full-match here.

Random filter-rules example:

- apparmor==DENIED && profile~!/^chromium(-.*)?/
+ uid=E=myuser # print events with that key in any record, unless dropped by previous rule
- auid=E=myuser && uid=E=root && profile~/-ux$/ # drop  profile=...-ux RECORDS in matched events
- / comm=nft(-\S+)$/ && uid=E=root # drop EVENTS ending with that comm= match
- E/(?m)^type=LOGIN .* uid=root .* res=yes$/ && proctitle=E=/usr/bin/cron -f
  && E/(?m)^type=SYSCALL .* auid=root ([esf]*[ug]id=root )+ses=\d+ comm=cron exe=/usr/bin/cron /
++ /^tail:/ && !/following new file|has become inaccessible: No such file or directory/

To understand how these rules work, simply go over them top-to-bottom,
 stop at the first one that applies, and if it has "-" prefix then record or event
 (if last/only match in &&-chain has E flag) is dropped/ignored, or printed otherwise.
'''

class ARX:

	def __init__(self, line, act=True):
		arxs = self.arx_list = list()
		while line.strip():
			rx, _, line = line.partition(' && ')
			if not rx: continue
			e = adict(neg=False, fm=False, ev=False, key='')
			if not ( (m := re.fullmatch(r'(\w+~)?([!iImME]+)?/(.+)/', rx))
					or (m := re.fullmatch(r'(\w+)=([!iImME]+)?=(.+)', rx)) ):
				if arxs: raise ValueError(f'Chained regexps must be /.../-wrapped: {rx!r}')
				arxs.append(adict(e, rx=re.compile(rx, re.I))); continue
			key, flags, rx = (g or '' for g in m.groups())
			if key and not key.endswith('~'):
				s = ''; ss = sss = rx + (line and f' && {line}')
				while ss and ss[0] == '"': # read json-quoted value
					try: sx, ss = ss[1:].split('"', 1); s += f'"{sx}"'
					except ValueError: raise ValueError(
						f'Unclosed double-quotes in value: {sss!r}' ) from None
				if s: line, rx = ss, json.loads('"' + s[1:-1].replace('""', r'\u0022') + '"')
				rx, flags = re.escape(rx), flags.translate(dict(zip(b'mM', 'Mm')))
			arxs.append(adict( e, key=key.rstrip('~'),
				neg='!' in flags, fm='M' in flags, ev='E' in flags,
				rx=re.compile(rx, re.NOFLAG if 'I' in flags else re.I) ))
		self.act, self.ev = bool(act), any(e.ev for e in arxs)

	def __str__(self): return '-+'[self.act] + ' ' + ' && '.join(
		(f'{e.key}~' if e.key else '') + ( ' !'[e.neg] + ' E'[e.ev]
			+ 'I '[bool(e.rx.flags & re.I)] + ' M'[e.fm] ).replace(' ', '')
		+ f'/{e.rx.pattern}/' for e in self.arx_list )
	def __repr__(self): return f'<ARX[ {self} ]>'

	def check(self, ev, evr=None, evrs=list()):
		'Returns match info, to apply .act to ev/evr as-needed'
		e, evr = None, evr or adict(_line=ev)
		for e in self.arx_list:
			e_chk = getattr(e.rx, ['search', 'fullmatch'][e.fm])
			e_chk = lambda s,_rx=e_chk: e.neg ^ bool(_rx(s))
			if e.ev:
				if e.key: # checks all event records, not just current one
					if not any(e_chk(str(evr.get(e.key, ''))) for evr in evrs if evr._line): return
				elif not e_chk(ev): return
				continue
			if e.key:
				if not e_chk(str(evr.get(e.key, ''))): return
			elif not e_chk(evr._line): return
		if not e: return # empty rule?
		return adict(rec=False, ev=True) if e.ev else adict(ev=False, rec=True)

def filter_file_parse(p):
	with open(p) as src: src = src.readlines()
	lines, ev_rules, noise_rules = list(), list(), list()
	for line in src:
		if line.startswith('#'): continue
		if not (line := line.split(' # ')[0].rstrip()): continue
		if line.startswith(' ') and lines: lines[-1] += line[1:]; continue
		lines.append(line)
	for line in lines:
		if (ls := line.lstrip()).startswith('- '): ev_rules.append(ARX(line[2:], False))
		elif ls.startswith('+ '): ev_rules.append(ARX(line[2:], True))
		elif ls.startswith('++ '): noise_rules.append(ARX(line[3:]))
		else: raise ValueError( 'All rules in -f/--filter-file'
			f' must have +/- or ++ prefix, it is missing here: {line!r}')
	if not (ev_rules or noise_rules): logging.getLogger('parse.filter') \
		.warning('Filter-file appears to have no valid rules in it')
	def _ev_filter(evrs, ev=None):
		for evr in evrs:
			for arx in ev_rules:
				if ev is None: ev = format_event(evrs)
				if not (res := arx.check(ev, evr, evrs)): continue # no match
				if not arx.act:
					if res.ev: list(evr.update(_line='') for evr in evrs)
					elif res.rec: evr._line, ev = '', None # combined ev changed too
				break
			if not (evrs := list(evr for evr in evrs if evr._line)): break
	return _ev_filter, lambda line: any(arx.check(line) for arx in noise_rules)


def main(args=None):
	import argparse
	dd = lambda text: re.sub(r' \t+', ' ', tw.dedent(text).strip('\n') + '\n').replace('\t', '  ')
	parser = argparse.ArgumentParser(
		formatter_class=argparse.RawTextHelpFormatter, description=dd('''
			Follow and decode audit messages, either from journalctl output, syslog or auditd logs.
			Default is to run/follow journalctl, pretty-printing audit events, separated
				by hyphen-line and split over multiple lines if too long, with [<type-id>] prefix.'''))

	parser.add_argument('--debug', action='store_true', help='Verbose stderr logging.')

	group = parser.add_argument_group('Input options')
	group.add_argument('-o', '--journalctl-opts', action='append', metavar='opts', help=dd('''
		Additional options/arguments to pass to journalctl.
		Will be split on spaces, unless option is used multiple times.
		Example: -o="--since=-1h SYSLOG_IDENTIFIER=audit"'''))
	group.add_argument('-i', '--stdin', action='store_true', help=dd('''
		Read from stdin instead of running journalctl, e.g pipe from "tail -F auditd.log".'''))
	group.add_argument('-I', '--stdin-format', metavar='fmt', help=dd('''
		Stdin log format - journal, auditd or syslog. Auto-detected from first line by default.'''))
	group.add_argument('-t', '--flush-timeout', type=float, metavar='sec', default=0.1, help=dd('''
		Timeout for waiting on more records of audit event, before using it as it is.
		Can be relevant when input is a slow connection/pipe. Default: %(default)ss'''))

	group = parser.add_argument_group('Output format and pretty-printing')
	group.add_argument('--raw', action='store_true',
		help='Output single record per line, without splitting, disable/override separators.')
	group.add_argument('-s', '--sep', metavar='char ["x" count]', help=dd('''
		Separator char and optional count of these to use between multi-line audit events/msgs.
		Default: -s=-x80, empty or no arg can be used for empty line.'''))
	group.add_argument('-l', '--line-len', type=int, metavar='n', default=95, help=dd('''
		Max length of individual lines in the output, to split longer ones. Default: %(default)s'''))
	group.add_argument('-r', '--reltime', action='store_true',
		help='Print monotonic timestamp relative to first event before every line.')
	group.add_argument('-d', '--difftime', action='store_true',
		help='Print timestamp since last logged event on each line.')
	group.add_argument('-p', '--auid-prefix', action='store_true',
		help='Add audit-id prefix to record lines, after timestamps.')
	group.add_argument('-P', '--auid-prefix-tag', action='store_true',
		help='Prepend more readable short and distinctive base64 tag, based on audit-id.')

	group = parser.add_argument_group('Output filtering')
	group.add_argument('-F', '--grep-str', metavar='string', help=dd('''
		Simple filtering - print only events (can have multiple records/lines) with substring.'''))
	group.add_argument('-f', '--filter-file', metavar='file', help=dd('''
		Config file for more complex filtering, with a list of allow/deny
			rules to filter audit records, events or other lines by, before output.
		Implies --raw output mode, as regexps in rules there apply against that.
		Run with --filter-file=help to print information about format for this file and exit.'''))

	opts = parser.parse_args(sys.argv[1:] if args is None else args)

	for old, new in dict( DEBUG='DEBUG', INFO='INFO',
			WARNING='WARN', ERROR='ERR', CRITICAL='FATAL' ).items():
		logging.addLevelName(getattr(logging, old), new)
	logging.basicConfig(
		level=logging.DEBUG if opts.debug else logging.INFO, style='{',
		format='{asctime} {name} {levelname:5} :: {message}', datefmt='%Y-%m-%dT%H:%M:%S' )

	noise_filter = None
	if opts.filter_file == 'help': return print(filter_file_info)
	elif opts.filter_file:
		if opts.grep_str: parser.error(
			'Using -F/--grep-str alongside -f/--filter-file is not supported' )
		ev_filter, noise_filter = filter_file_parse(opts.filter_file)
	elif gs := opts.grep_str: ev_filter = ( lambda evrs:
		any(gs not in evr._line for evr in evrs) or list(evr.update(_line='') for evr in evrs) )
	else: ev_filter = None

	out_raw = opts.raw or opts.filter_file
	out = open(sys.stdout.fileno(), 'w', 1) # line-buffered
	out = ft.partial(print, file=out, flush=True)
	signal.signal(signal.SIGINT, signal.SIG_DFL)

	stream_fmt, journalctl_opts = None, opts.journalctl_opts or list()
	if len(journalctl_opts) == 1: journalctl_opts = journalctl_opts[0].strip().split()
	if not opts.stdin:
		proc = sp.Popen('journalctl -af -o json'.split() + journalctl_opts, stdout=sp.PIPE)
		atexit.register(proc.terminate)
		stream, stream_fmt = proc.stdout, input_fmt.journal
	else:
		stream = sys.stdin
		if opts.stdin_format: stream_fmt = input_fmt[opts.stdin_format]

	sep = '-' if opts.sep is None else opts.sep.strip()
	if len(sep) > 1:
		sep, sep_c = sep.split('x', 1)
		sep, sep_c = sep.strip(), int(sep_c)
	else: sep_c = min(80, opts.line_len)
	if sep: sep *= sep_c
	if out_raw: sep = ''

	ts0 = ts0_ev = sep_collapse = None; val_esc = '\ue157'
	twx = tw.TextWrapper( width=opts.line_len, tabsize=2, initial_indent='',
		subsequent_indent='  ', break_long_words=False, break_on_hyphens=False )
	for ev in input_parse( stream, stream_fmt,
			noise_filter=noise_filter, flush_timeout=opts.flush_timeout ):
		if isinstance(ev, str): out(ev); continue # lines passed through noise_filter
		if not ts0: ts0 = ev.ts
		if not ts0_ev: ts0_ev = ev.ts

		for evr in ev.rs:
			prefix = ''
			if opts.reltime: prefix = f'[{ev.ts - ts0:>9.3f}] '
			if opts.difftime: prefix += f'[{ev.ts - ts0_ev:>7.3f}] '; ts0_ev = ev.ts
			if opts.auid_prefix: prefix += f'audit({ev.auid}): '
			if opts.auid_prefix_tag: prefix += f'{str_hash(ev.auid, 4)} '
			evr._prefix = prefix; format_record_line(evr, val_esc)

		ev.rs = list(evr for evr in ev.rs if evr._line)
		if ev_filter:
			ev_filter(ev.rs)
			ev.rs = list(evr for evr in ev.rs if evr._line)
		if not ev.rs: continue # event or all records filtered-out

		if not out_raw: # move type info to nicer prefix
			for evr in ev.rs:
				if (t := evr.get('type')): evr._prefix += (f'[{t}]' if t.isdigit() else t) + ' '
				evr.type = None; format_record_line(evr)

		ev_msg = ( format_event(ev.rs, prefix=True)
			if out_raw else format_event(ev.rs, twx, val_esc, prefix=True) )
		if sep:
			if not sep_collapse: ev_msg = f'{sep}\n{ev_msg}'
			ev_msg += f'\n{sep}'
		out(ev_msg); sep_collapse = True

if __name__ == '__main__':
	try: sys.exit(main())
	except BrokenPipeError: # stdout pipe closed
		os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
		sys.exit(1)
