#!/usr/bin/env python

import itertools as it, collections as cs, hashlib as hl, pathlib as pl
import os, sys, re, shutil, fnmatch, base64

try:
	import cryptography.x509 as c_x509
	import cryptography.hazmat.primitives.hashes as c_hashes
except ImportError: c_x509 = None


p_err = lambda *a,**kw: print('ERROR:', *a, **kw, file=sys.stderr, flush=True)

class adict(dict):
	def __init__(self, *args, **kws):
		super().__init__(*args, **kws)
		self.__dict__ = self

def str_cut(s, max_len=80, len_bytes=False, repr_fmt=False, ext=' ...[{s_len}]'):
	'''Truncates longer strings to "max_len", adding "ext" suffix.
		Squashes line-breaks to ⏎, unless bytes or repr_fmt are used for full repr() escaping.'''
	if isinstance(s, bytes): s, repr_fmt = s.decode('utf-8', 'replace'), True
	if not isinstance(s, str): s = str(s)
	if repr_fmt: s = repr(s)[1:-1] # for logs and such, to escape all weird chars
	else: s = s.replace('\n', '⏎')
	s_len, ext_tpl = f'{len(s):,d}', ext.format(s_len='12/345')
	if max_len > 0 and len(s) > max_len:
		s_len = f'{max_len}/{s_len}'
		if not len_bytes: s = s[:max_len - len(ext_tpl)] + ext.format(s_len=s_len)
		else:
			n = max_len - len(ext_tpl.encode())
			s = s.encode()[:n].decode(errors='ignore') + ext.format(s_len=s_len)
	return s

def b64_hash(data, n=10, person=b'cacertsw', **b2_kws):
	if not isinstance(data, bytes): data = data.encode()
	digest = hl.blake2s(data, person=person, **b2_kws).digest()
	while True:
		b64 = base64.urlsafe_b64encode(digest).decode().replace('_', '').replace('-', '')
		if len(b64) >= n: return b64[:n]
		digest = hl.blake2s(digest, person=person, **b2_kws).digest()


def parse_ca_conf(src, name=None):
	p_err_sec = lambda s: p_err(f'{src_pre} {s}')
	sec, props, pem, pem_str = None, dict(), list(), None
	ca_conf_list = cs.defaultdict(list)
	for n, line in enumerate(it.chain(src, ['[end]']), 1):
		src_name = name or src.name
		src_pre = f'[ {src_name}:{n} ]'
		if re.search(r'^\s*(#|$)', line): continue
		elif m := re.search(r'^\s*\[(\S+)\]\s*$', line):
			if sec:
				obj = adict(sec=sec, props=props.copy(), pem=pem_str, conf=src_name)
				if not (label := props.get('label')):
					p_err_sec(f'Skipping {sec} without label :: {str_cut(obj)}')
				elif pem_str is None:
					p_err_sec(f'Dropping no-PEM {sec} :: {str_cut(obj)}')
				else: ca_conf_list[label.strip('"')].append(obj)
			sec = m[1]; props.clear(); pem.clear(); pem_str = None
			continue
		elif sec:
			if m := re.search(r'^\s*(\S+):\s+(\S.*?)\s*$', line):
				if m[1] in props: p_err_sec(f'Skipping duplicate property :: {line.strip()}')
				else: props[m[1]] = m[2]
				continue
			elif not pem and re.search(r'^--+\s*BEGIN .*--+$', line): pem.append(line); continue
			elif pem and re.search(r'^[a-zA-Z0-9+/=]+$', line): pem.append(line); continue
			elif pem and re.search(r'^--+END .*--+$', line):
				pem.append(line); pem_str = ''.join(pem); pem.clear(); continue
			p_err_sec(f'Unrecognized section line :: {line.strip()}')
		else: p_err_sec(f'Unrecognized line :: {line.strip()}')
	return ca_conf_list

def print_ca_conf_list(ca_conf_list):
	for n, label in enumerate(ca_conf_list, 1):
		print(n, label)
		if not c_x509: continue
		certs = list( (obj.pem, obj.conf)
			for obj in ca_conf_list[label] if 'BEGIN CERTIFICATE' in obj.pem )
		for pem, conf in certs:
			pre = f'{conf} ' if len(certs) > 1 else ''
			cert = c_x509.load_pem_x509_certificate(pem.encode())
			for alg in 'SHA1', 'SHA256':
				fp = cert.fingerprint(getattr(c_hashes, alg)()).hex(':').upper()
				print(f'   {pre}{alg:<6s} = {fp}')
			for a in cert.subject: print(f'   {pre}{a.oid._name}: {a.value}')
			print(f'   {pre}{a.oid._name}: {a.value}')
			print()

def print_ca_conf_p11k(ca_conf_list, file=sys.stdout):
	p = lambda s='': print(s, file=file)
	for n, obj in enumerate(it.chain.from_iterable(ca_conf_list.values())):
		if n: p()
		p(f'[{obj.sec}]')
		for k, v in obj.props.items(): p(f'{k}: {v}')
		p(obj.pem.strip())


def main(argv=None):
	import argparse, textwrap
	dd = lambda text: re.sub( r' \t+', ' ',
		textwrap.dedent(text).strip('\n') + '\n' ).replace('\t', '  ')
	parser = argparse.ArgumentParser(
		formatter_class=argparse.RawTextHelpFormatter,
		usage='%(prog)s [opts] [-w whitelist-file] [trust-dir]', description=dd('''
			Trim down list of trusted CAs used by ca-certificates/p11-kit.
			Unlike built-in p11-kit tools, which use blacklist logic, this script does the
				opposite - picks couple useful CAs according to whitelist, discards all others.
			Intended to be run when contents of trust-dir change, e.g. via package manager hook.
			Tested to work with Mozilla's set of CA certs in p11-kit format.'''))

	parser.add_argument('trust_dir', nargs='?',
		default='/usr/share/ca-certificates/trust-source', help=dd('''
			ca-certificates/trust-source directory,
				where CA PEM bundles are stored in p11-kit ini-like format.
			All files in the directory will be filtered and replaced.
			Default: %(default)s'''))
	parser.add_argument('-w', '--whitelist', nargs='?', help=dd('''
		List of p11-kit object labels to include in resulting CA bundle, ignoring all others.
		One per line, can include shell-glob/fnmatch wildcards.
		Must be specified for normal filtering mode, but not required for --list-all.'''))

	group = parser.add_argument_group('Non-essential file/dir names')
	group.add_argument('-b', '--backup-dir', default='bak', metavar='dir', help=dd('''
		Dir to copy original unprocessed file(s) to,
			just in case, and to maybe re-process them later.
		Can be relative to trust-dir. Default: %(default)s'''))
	group.add_argument('-x', '--skip-re',
		default=r'(?i)^(README(\..*)?|\.txt)$', metavar='regexp', help=dd('''
			Regexp (python re syntax) to match name(s) of files in trust-dir to skip processing.
			These files will simply be moved into -b/--backup-dir, with their contents ignored.
			Empty - don't skip anything. Default: %(default)s'''))

	group = parser.add_argument_group('List/print and debug options')
	group.add_argument('-p', '--print', action='store_true',
		help='Print all filtered p11-kit configuration to stdout, same as written to files.')
	group.add_argument('-L', '--list-all', action='store_true', help=dd('''
		List all p11-kit object labels and exit. Implies -n/--dry-run.
		Also prints certificate information if cryptography.io module is available.'''))
	group.add_argument('-l', '--list', action='store_true',
		help='Like -L/--list-all, but only list filtered p11-kit objects.')
	group.add_argument('-n', '--dry-run', action='store_true',
		help='Do not create or replace any files, just parse, apply all filtering and exit.')
	opts = parser.parse_args(sys.argv[1:] if argv is None else argv)

	list_mode = opts.list or opts.list_all
	dry_run = opts.dry_run or list_mode
	if not opts.list_all:
		if not opts.whitelist: parser.error('-w/--whitelist file must be specified')
		whitelist = list(filter( None,
			pl.Path(opts.whitelist).read_text().splitlines() ))

	ca_lists = list(p for p in pl.Path(opts.trust_dir).iterdir() if p.is_file())
	bak_dir = pl.Path(opts.trust_dir) / opts.backup_dir
	if not dry_run: bak_dir.mkdir(mode=0o700, exist_ok=True)

	tmp_files = list()
	try:
		ca_conf_list = cs.defaultdict(list)
		for p in ca_lists:
			src_ca_list, src_is_origin = dict(), True

			if not (rx := opts.skip_re) or not re.search(rx, p.name):
				with p.open() as src:
					src_hash = (m := re.fullmatch(
						r'#.*\[([a-zA-Z0-9]{10})\]', line := src.readline().strip() )) and m[1]
					if src_hash and src_hash == b64_hash(lines := src.read()):
						src_is_origin, lines = False, lines.splitlines(keepends=True)
					else: src.seek(0); lines = src
					src_ca_list.update(parse_ca_conf(lines, p.name))
					if not opts.list_all:
						for label in list(src_ca_list):
							if not any(fnmatch.fnmatchcase(label, pat) for pat in whitelist):
								del src_ca_list[label]
					if list_mode:
						for label, cas in src_ca_list.items(): ca_conf_list[label].extend(cas)

			if opts.print:
				print('-'*20, p.name)
				print_ca_conf_p11k(src_ca_list)

			if dry_run:
				with open(os.devnull, 'w') as null:
					print_ca_conf_p11k(src_ca_list, null)
				continue

			if not src_ca_list:
				tmp_files.append((p, bak_dir / p.name))
				continue

			if src_is_origin: # don't overwrite original backups
				shutil.copyfile(p, bak_tmp := pl.Path(
					str(bak := bak_dir / f'{p.name}') + '.old' ))
				tmp_files.append((bak_tmp, bak))
			with (p_tmp := bak_dir / f'{p.name}.new').open('w+') as tmp:
				tmp_files.append((p_tmp, p))
				tmp.write( line := '## Generated by'
					f' ca-certs-apply-whitelist from {p.name} [{b64_hash("")}]\n' )
				pos_hash, pos_data = line.rfind('[') + 1, tmp.tell()
				tmp.write('\n'); print_ca_conf_p11k(src_ca_list, tmp)
				tmp.seek(pos_data); src_hash = b64_hash(tmp.read())
				tmp.seek(pos_hash); tmp.write(src_hash)

		if list_mode: print_ca_conf_list(ca_conf_list)

		if not dry_run: # put all new/backup files into place
			while tmp_files:
				p_tmp, p = tmp_files.pop()
				p_tmp.rename(p)

	finally:
		if dry_run: tmp_files.clear()
		for tmp, bak in tmp_files: tmp.unlink(missing_ok=True)

if __name__ == '__main__': sys.exit(main())
