#!/usr/bin/env python

import os, sys, collections as cs

def reorder_paths(argv):
	cmd, args = argv[0], argv[1:]
	if not args or not args[0].startswith('-'): return argv
	args, xargs = cs.deque(args), args
	for p in reversed(xargs):
		if not p.startswith('-') and os.path.isdir(p):
			print('Reordering path at the end:', p, file=sys.stderr)
			args.appendleft(args.pop())
			continue
		break
	args.appendleft(cmd)
	return list(args)

args = reorder_paths(sys.argv)
os.execvp('/usr/bin/find', args)
