#!/bin/bash

[[ -z "$1" || "$1" =~ ^-?-h(elp)?$ ]] && { echo >&2 "Usage: $0 site [port]"; exit 1; }
site=$1 port=${2:-443}

openssl s_client -connect "${site}:${port}" </dev/null 2>/dev/null |
	openssl x509 -fingerprint -noout -sha1
