#!/usr/bin/env python

import os, sys, re, time, math

def td_parse(td, _tds=dict(
		d=1*86400, day=1*86400, h=3600, hr=3600, hour=3600,
		m=60, min=60, minute=60, s=1, sec=1, second=1, ms=1e-3, us=1e-6 )):
	'Parse [[HH:]MM:]SS or e.g. 5h30m and such time-deltas to seconds'
	if td is None: return
	if isinstance(td, (int, float)): return td
	delta, td_re = 0, ('(?i)^[-+]?' + ''.join(
		fr'(?P<{k}>\d+{k}{"s?" if len(k)>2 else ""}\s*)?' for k, v in
		sorted(_tds.items(), key=lambda kv: (-kv[1], -len(kv[0]))) ) + '$')
	if not ((m := re.search(td_re, td.strip())) and any(m.groups())):
		h, m, s = (v.strip(': ') for v in ('::' + td).rsplit(':', 2))
		try: return float(s or 0) + float(m or 0) * 60 + float(h or 0) * 3600
		except: raise ValueError(f'Unrecognized timespan value format: {td!r}')
	for k, v in _tds.items():
		if not m.group(k): continue
		delta += v * int(''.join(filter(str.isdigit, m.group(k))) or 1)
	return delta

def td_repr(delta, units_max=2, units_res=None, _units=dict(
		h=3600, m=60, s=1, y=365.2422*86400, mo=30.5*86400, w=7*86400, d=1*86400 )):
	res, s, n_last = list(), abs(delta), units_max - 1
	units = sorted(_units.items(), key=lambda v: v[1], reverse=True)
	for unit, unit_s in units:
		val = math.floor(s / unit_s)
		if not val:
			if units_res == unit: break
			continue
		if len(res) == n_last or units_res == unit:
			val, n_last = round(s / unit_s), True
		res.append(f'{val:.0f}{unit}')
		if n_last is True: break
		s -= val * unit_s
	return ' '.join(res) if res else '<1s'

def token_bucket_rate(spec, negative_tokens=False):
	'''Token-bucket rate-limit iterator. Spec: {<rate>|<rate>/<td>}[:<burst>]
		Examples: 2.5:5 (rate=2.5/s burst=5), 3/5m:10 (rate=3-in-5m burst=10), 5, 9:30.
		Yields None if there's enough tokens or delay (float). iter.send(N) to use N tokens.
		Borrows below zero tokens with negative_tokens set.
		Simple "inf" value means "always None", or "0" for "infinite delays".'''
	try:
		if len(s := spec.rsplit(':', 1)) == 1: rate, burst = spec, 1.0
		else: rate, burst = s[0], float(s[1])
		if len(s := rate.split('/', 1)) == 1: rate = float(rate)
		else: rate = float(s[0]) / td_parse(s[1])
	except: raise ValueError(f'Invalid format for rate-limit: {spec!r}')
	if rate == float('inf'):
		while True: yield None
	elif rate <= 0:
		while True: yield 2**31 # safe "infinite delay" value
	n, ts, d = max(0, burst - 1), time.monotonic(), (yield) or 1
	while True:
		n = min(burst, n - rate * (ts - (ts := time.monotonic())))
		if n >= d: n, d = n - d, (yield) or 1; continue
		n, d = (n - d if negative_tokens else n), (yield (d - n) / rate) or 1

def main(args=None):
	import argparse, textwrap
	dd = lambda text: re.sub( r' \t+', ' ',
		textwrap.dedent(text).strip('\n') + '\n' ).replace('\t', '  ')
	parser = argparse.ArgumentParser(
		usage='%(prog)s [options]', formatter_class=argparse.RawTextHelpFormatter,
		description='Rate-limit passing stdin lines through, indicating when rate-limit-drop starts.')
	parser.add_argument('rate_limit', help=dd('''
		Token bucket rate-limiting paramters for passing
			stdin lines through to stdout, in <rate>[/<time-delta>][:<burst>] format.
		Default logic is: each stdin line takes a "token", dropping it if there're none at the moment.
		Examples: 2.5:5 (rate=2.5/s burst=5), 3/5m:10 (rate=3-in-5m burst=10), 9:30, 5 (5:1).'''))
	parser.add_argument('-q', '--quiet', action='store_true',
		help='Do not print extra messages when rate-limits get triggered.')
	parser.add_argument('-p', '--pass-over-limit', action='store_true',
		help='Invert rate-limiting logic to only pass lines through when over the limit.')
	opts = parser.parse_args(sys.argv[1:] if args is None else args)

	tbf = token_bucket_rate(tbf_rl := opts.rate_limit)
	tbf_pass, tbf_active = opts.pass_over_limit, False
	pr, pw = sys.stdin.buffer, sys.stdout.buffer
	for line in pr:
		if not ((td := next(tbf)) is None) ^ tbf_pass:
			if not (tbf_active or tbf_pass or opts.quiet):
				pw.write(f'[ rate-limit {tbf_rl} active for {td_repr(td)} ]\n'.encode()); pw.flush()
			tbf_active = True; continue
		pw.write(line); pw.flush(); tbf_active = False

if __name__ == '__main__':
	try: sys.exit(main())
	except BrokenPipeError: # stdout pipe closed
		os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
		sys.exit(1)
