#!/bin/bash

usage() {
	bin=$(basename $0)
	echo >&2 "Usage:"
	echo >&2 "  $bin <ssh -L forwarding spec> <ssh destination spec> [<ssh opts>]"
	echo >&2 "  $bin <ssh -L forwarding spec> <ssh destination spec> { kill | -k }"
	echo >&2
	echo >&2 "Example:"
	echo >&2 "  $bin 8080:127.0.0.1:80 root@my.example.host"
	exit ${1:-0}
}
[[ -z "$1" || -z "$2" || "$#" -gt 3 || "$1" = -h || "$1" = --help ]] && usage

pid_file="/tmp/.$(basename $0).$(echo "$1.$2" | md5sum | cut -b-5)"

[[ "$3" != kill && "$3" != -k ]] || {
	pid=$(cat "$pid_file" 2>/dev/null)
	[[ -n "$pid" ]] || exit 1
	flock -n 3 3<"$pid_file" && exit 1
	pgrp=$(ps -o pgrp= "$pid" | tr -d '\040\011\012\015')
	[[ -n "$pgrp" && "$pgrp" -gt 1 ]] || exit 1
	exec kill -- -"$pgrp"
}

touch "$pid_file"
flock -n 3 3<"$pid_file" || exit 0
exec 3>"$pid_file"

( flock -n 3 || exit 0
	trap "rm -f '$pid_file'" EXIT
	while :; do
		ssh\
			-oControlPath=none\
			-oControlMaster=no\
			-oServerAliveInterval=3\
			-oServerAliveCountMax=5\
			-oConnectTimeout=5\
			-o PasswordAuthentication=no\
			-o NumberOfPasswordPrompts=0\
			-qyTnN $3 -L "$1" "$2"
		sleep 5
	done ) &

echo $! >&3
exit 0
