#!/bin/bash

usage() {
	bin=$(basename $0)
	echo >&2 "Usage:"
	echo >&2 "  $bin [-1] <ssh -L forwarding spec> <ssh destination spec> [<ssh opts>]"
	echo >&2 "  $bin <ssh -L forwarding spec> <ssh destination spec> { kill | -k }"
	echo >&2
	echo >&2 "Example:"
	echo >&2 "  $bin 8080:127.0.0.1:80 root@my.example.host"
	echo >&2
	echo >&2 "Starts non-interactive ssh -L tunnel through specified destination host,"
	echo >&2 " saving pid file in /tmp, which can be used to stop tunnel via kill/-k option."
	echo >&2 "When setting up tunnel for the first time,"
	echo >&2 " -1 (oneshot) option can be used to test it in the foreground."
	exit ${1:-0}
}
[[ "$#" -lt 2 || "$1" = -h || "$1" = --help ]] && usage

oneshot= ssh_opts_ext= fwd= dst=
pid_file="/tmp/.$(basename $0).$(echo "$1.$2" | md5sum | cut -b-5)"

[[ "$1" != -1 ]] || { oneshot=t; shift; }
fwd=$1 dst=$2
shift; shift

if [[ "$1" = kill || "$1" = -k ]]; then
	pid=$(cat "$pid_file" 2>/dev/null)
	[[ -n "$pid" ]] || exit 1
	flock -n 3 3<"$pid_file" && exit 1
	pgrp=$(ps -o pgrp= "$pid" | tr -d '\040\011\012\015')
	[[ -n "$pgrp" && "$pgrp" -gt 1 ]] || exit 1
	exec kill -- -"$pgrp"
else ssh_opts_ext=( $@ ); fi

ssh_opts=(
	-oControlPath=none
	-oControlMaster=no
	-oServerAliveInterval=3
	-oServerAliveCountMax=5
	-oConnectTimeout=5
	-oBatchMode=yes
	-oPasswordAuthentication=no
	-oNumberOfPasswordPrompts=0
	-oExitOnForwardFailure=yes
	-TnN
)
[[ -n "$oneshot" ]] || ssh_opts+=( -qy )
ssh_opts+=( "${ssh_opts_ext[@]}" )

[[ -z "$oneshot" ]] \
	|| exec ssh "${ssh_opts[@]}" -L "$fwd" "$dst"

touch "$pid_file"
flock -n 3 3<"$pid_file" || exit 0
exec 3>"$pid_file"
( flock -n 3 || exit 0
	trap "rm -f '$pid_file'" EXIT
	while :; do
		ssh "${ssh_opts[@]}" -L "$fwd" "$dst"
		sleep 5
	done ) &

echo $! >&3
exit 0
