#!/bin/bash

PID="/tmp/.$(basename $0).$(echo "$1.$2" | md5sum | cut -b-5)"
touch "$PID"

flock -n 3 3<"$PID" || exit 0
exec 3>"$PID"

( flock -n 3 || exit 0
	while :; do
		ssh\
			-oControlPath=none\
			-oControlMaster=no\
			-oServerAliveInterval=3\
			-oServerAliveCountMax=5\
			-oConnectTimeout=5\
			-o PasswordAuthentication=no\
			-o NumberOfPasswordPrompts=0\
			-qyTnN $3 -L "$1" "$2"
		sleep 5
	done ) &

echo $! >&3
exit 0
