#!/usr/bin/env python2
# -*- coding: utf-8 -*-
from __future__ import print_function

import os, sys, termios

def termio_echo(state, fd=None):
	if fd is None: fd = sys.stdin.fileno()
	iflag, oflag, cflag, lflag, ispeed, ospeed, cc = termios.tcgetattr(fd)
	if state: lflag |= termios.ECHO
	else: lflag &= ~termios.ECHO
	termios.tcsetattr( fd, termios.TCSANOW,
		[iflag, oflag, cflag, lflag, ispeed, ospeed, cc] )

termio_echo(False)
try:
	for line in iter(sys.stdin.readline, ''): sys.stdout.write(line)
finally: termio_echo(True)
