#!/bin/bash

script_info='Generic linux distro VM with grub and partitioned disk img.'


### Management

root=/mnt/volatiles/vms
dst="$root"/linux/live.dump
telnet_port=8201
vde_mac=52:54:00:12:34:61
vde_path=~/tmp/vde
dump_inc=
restore=
net_only=
img=linux/install.qcow2.inc
video=( -nographic )
fs=

[[ "$1" = -i || "$1" = --img ]] && { img=$(realpath "$2"); shift; shift; }
[[ "$1" = -f || "$1" = --fs ]] && { fs=t; shift; }

[[ "$1" = -g || "$1" = --graphic ]] && {
	video=( -vga std )
	# video+=( -display gtk )
	# video+=( -display vnc 0 )
	shift
}

case "$1" in
	d|dump)
		[[ "$2" = -i ]] && { dump_inc=-i; shift; }
		[[ -n "$2" ]] && {
			touch "$2" || exit 1
			dst=$(realpath "$2")
		}
		echo "Dumping to: $dst"
		ncat -t 127.0.0.1 "$telnet_port" <<EOF
stop
migrate_set_speed 4g
migrate -d $dump_inc "exec:lzop -c > $dst"
EOF
		echo
		while :; do
			echo 'info migrate' | ncat -t 127.0.0.1 "$telnet_port" |
				grep -aq '^Migration status:[[:space:]]*completed[[:space:]]*$'
			pipe=( "${PIPESTATUS[@]}" )
			[[ ${pipe[0]} -ne 0 || ${pipe[1]} -ne 0 ]] && exit 1
			[[ ${pipe[2]} -eq 0 ]] && {
				echo 'quit' | ncat -t 127.0.0.1 "$telnet_port"
				echo "Done"
				ls -lah "$dst"
				exit 0
			}
			sleep 1 || exit 1
		done ;;

	r|restore)
		[[ -n "$2" ]] && dst=$2
		echo "Restoring from: $dst"
		[[ -f "$dst" ]] || { echo >&2 "FIle not found: $dst"; exit 1; }
		restore=t ;;

	m|monitor) exec rlwrap ncat -t 127.0.0.1 "$telnet_port" ;;
	n|net|net-only) net_only=t ;;

	'') ;;
	*)
		echo >&2 "Usage: $0 [ {-i|--img} basename] [-g|--graphic] [-f|--fs] \\"
		echo >&2 "  [ { d | dump } [path] | { r | restore } [-i] [path] | { m | monitor } | { n | net-only } ]"
		cat >&2 <<EOF

$script_info

Cheatsheet for qemu-img:
  qemu-img create -f qcow2 install.qcow2 10G
  qemu-img create -b install.qcow2 -f qcow2 install.qcow2.inc
  qemu-img commit install.qcow2.inc && rm install.qcow2.inc

Cheatsheet to init new cloudimg:
  qemu-nbd -c /dev/nbd0 install.qcow2.inc && fsck -a /dev/nbd0p1 && mount /dev/nbd0p1 /mnt/nbd
   && chmod a+r /mnt/nbd/{vmlinuz,initrd.img}
   && cat ~/.ssh/authorized_keys > /mnt/nbd/root/.ssh/authorized_keys
   && cat ~/.ssh/authorized_keys > /mnt/nbd/home/ubuntu/.ssh/authorized_keys
   && touch /mnt/nbd/etc/cloud/cloud-init.disabled
   && rm -rf /mnt/nbd/etc/systemd/system/cloud-init.target.wants
   && umount /mnt/nbd && qemu-nbd -d /dev/nbd0

EOF
		exit 1 ;;
esac

cd "$root"


### Slugfest otherwise

modprobe kvm || exit 1
modprobe kvm-intel
modprobe kvm-amd


### VDE

mkdir -p "$vde_path"

cgrc vm/misc vde_switch\
	-s "$vde_path"/link.sock\
	-M "$vde_path"/mgmt.sock &
pid1=$!

for n in {0..50}; do
	[[ -e "$vde_path"/link.sock ]] && break
	sleep 0.1
done
[[ $n -eq 50 ]] && { echo >&2 "vde switch startup failed"; exit 1; }

cgrc vm/misc sudo vde_plug2tap\
	-s "$vde_path"/link.sock\
	vde &
pid2=$!

# Add a little delay if vde stuff is just starting
for n in {0..5}; do
	kill -0 $pid1 $pid2 2>/dev/null || break
	sleep 0.1
done

[[ -n "$net_only" ]] && exit 0


### Run qemu

qemu_opts=(
	-name "$(basename "$0")"

	-m 4096M
	-rtc base=utc,clock=host
	-monitor telnet:127.0.0.1:${telnet_port},server,nowait
	-usb -device usb-kbd -device usb-mouse
	-net nic,macaddr=${vde_mac},id=vde
	-net vde,sock="$vde_path"/link.sock
	-k en-us

	-enable-kvm
	-cpu host
	-smp 2
	"${video[@]}"

	-drive file="$img",if=virtio,aio=native,cache=writeback,cache.direct=on
	# -cdrom linux/install.iso
)

ulimit -c 0
export QEMU_AUDIO_DRV=none

[[ -n "$restore" ]] && qemu_opts+=( -incoming "exec:bsdcat $dst" )

exec cgrc vm/misc qemu-system-x86_64 "${qemu_opts[@]}"
