#!/bin/bash

usage() {
	bin=$(basename $0)
	echo >&2 "Usage: $bin file [file ...]"
	echo >&2 "Must be run from a git repo root, acts on HEAD."
	exit ${1:-0}
}
[[ -z "$1" || "$1" = -h || "$1" = --help ]] && usage

[[ -d .git || -n "$GIT_DIR" ]] || {
	echo "Error: must run this script from the root of a git repository"
	exit 1
}

set -e -o pipefail

# remove all paths passed as arguments from the history of the repo
git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch -- $@" HEAD

# remove the temporary history git-filter-branch otherwise leaves behind for a long time
rm -rf .git/refs/original/ \
	&& git reflog expire --expire-unreachable=now --all \
	&& git gc --aggressive --prune=now
