#!/bin/bash

step=15

[[ -z "$1" || -z "$2" || -n "$4" || "$1"= -h || "$1"= --help ]] && {
	cmd=$(basename "$0")
	echo >&2 "Usage: $cmd file-to-split.mp3 prefix [ chunk-len-in-minutes ]"
	echo >&2 "Example: $cmd some-long-book.mp3 slb"
	echo >&2 "  Resulting files will be: slb-001.mp3 slb-002.mp3 ..."
	echo >&2 "  Default length: $step min"
	exit 1
}

set -e -o pipefail
[[ -z "$3" ]] || step=$3
step=$(( $step * 60 ))

len=$( ffprobe "$1" 2>&1 |
	awk 'match($0,/Duration: (\S+)\./,a) {split(a[1],b,":");print b[1]*3600+b[2]*60+b[3]}' )
ext=${1##*.}

n=1
ns=$(( ($len / $step) + 1 ))

while [[ $n -le $ns ]]; do
	s=$(( ($n-1) * $step ))
	e=$(( $n * $step ))
	dst="${2}-$(printf '%03d' $n).${ext}"

	echo "---- $dst [$n/$ns, $s-$e]"

	ffmpeg -loglevel warning -y -i "$1" -acodec copy -vn -ss $s -to $e "$dst"
	(( n += 1 ))
done
