#!/bin/bash

dst=/tmp/media.img2tty.png
if [[ -z "$TOTTY_X" || -z "$TOTTY_Y" ]]
then read tty_rows tty_cols < <(stty size)
else tty_cols=$TOTTY_X tty_rows=$TOTTY_Y
fi
err=0

for p in "$@"; do
	[[ "$p" =~ https?:// ]] && {
		curl -s "$p" >"$dst"\
			|| { echo >&2 "Failed to fetch url: $p"; err=1; continue; }
		p=$dst
	}

	ct=$(file --brief --mime-type "$p")
	[[ "$ct" =~ ^image/ ]]\
		|| { echo >&2 "Unknown content type ($ct): $p"; err=1; continue; }
	[[ "$#" -gt 1 ]] && echo "--- $p"
	convert "$p" -resize "${tty_cols}"x "$dst" && img2xterm -p "$dst" || err=1
done

rm -f "$dst"
exit $err
