#!/bin/bash

usage() { echo >&2 "Usage: $0 [ -v ] N"; exit 1; }

verbose=
[[ "$1" = "-v" ]] && { verbose='-v'; shift; }
[[ -z "$1" || ! "$1" =~ ^[0-9]+$ ]] && usage
ufs="$1"

cs="csync2 -C ufs${ufs} $verbose"
cs_list=$(mktemp)

csync2 -C "ufs${ufs}" -M >"$cs_list" || exit 1
tac "$cs_list" >"${cs_list}.bak" || exit 1
mv "${cs_list}"{.bak,} || exit 1

awk '!/\.(mp3|flac|ogg|aac|m4a)$/ {print $4}' "$cs_list" |
while read p; do
	[[ -e "$p" ]] && continue
	$cs -rm "$p" && $cs -rf "$p" && $cs -ru "$p" || break
done

rm -f "$cs_list"
